version: '3.7'
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - ./config:/config
      - /mnt/harddrive/tubesync-downloads:/downloads
      - /mnt/harddrive/Media/Shows/The Martin Garrix Show:/downloads/martingarrixshow
    environment:
      - TZ=Asia/Kolkata
      - PUID=1000
      - PGID=1000
