version: '3.8'

services:
  oracle21c:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle21c
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=MYPDB
      - ORACLE_PWD=Oracle_123
      - ORACLE_SDTZ=Asia/Kolkata
    volumes:
      - ./oracle-data:/opt/oracle/oradata
      - ./oracle-backup:/opt/oracle/backup
