services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      TZ: "Asia/Kolkata"
      DIFFICULTY: "easy"
      OPS: "2535441434771218"
      SERVER_NAME: "Milind's Spaceship"
      ONLINE_MODE: true
      ALLOW_CHEATS: false
      ENABLE_LAN_VISIBILITY: true
      PVP: false
      VIEW_DISTANCE: 32
      TICK_DISTANCE: 4
    ports:
      - "19132:19132/udp"
      - "19132:19132"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
