services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    environment:
      MAIN_URL: $MAIN_URL
      FRONTEND_URL: $FRONTEND_URL
      NEXT_PUBLIC_BACKEND_URL: $NEXT_PUBLIC_BACKEND_URL
      JWT_SECRET: $JWT_SECRET
 
      # These defaults are probably fine, but if you change your user/password, update it in the
      # postiz-postgres or postiz-redis services below.
      DATABASE_URL: $DATABASE_URL
      REDIS_URL: $REDIS_URL
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true" # Required for self-hosting.
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - ./postiz-config:/config/
      - ./postiz-uploads:/uploads/
    ports:
      - 5000:5000
    networks:
      - postiz-network
      - db
    depends_on:
      postiz-redis:
        condition: service_healthy
 
  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./postiz-redis-data:/data
    networks:
      - postiz-network
 
networks:
  postiz-network:
    external: false
