services:
 flaresolverr:
   image: ghcr.io/flaresolverr/flaresolverr:latest
   container_name: flaresolverr
   environment:
     - LOG_LEVEL=${LOG_LEVEL:-info}
     - LOG_HTML=${LOG_HTML:-false}
     - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
     - TZ=Asia/Kolkata
   ports:
     - "${PORT:-8191}:8191"
   networks:
     - servarr
   restart: unless-stopped 

networks:
  servarr:
    name: servarr
    external: true

