version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8081:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: ${API_ENDPOINT} # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: ${CLIENT_ENDPOINT}
      SPOTIFY_PUBLIC: ${SPOTIFY_PUBLIC}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      CORS: ${CORS}

  mongo:
    container_name: mongo
    restart: always
    image: mongodb-raspberrypi4-unofficial-r6.0.11 # This doesn't exist anywhere, I had to build image that works with RPi
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "8082:3000"
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
