services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    networks:
      - servarr
    restart: unless-stopped

networks:
  servarr:
    name: servarr
    external: true
