services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    networks:
      - servarr
    volumes:
      - ./jellyfin_config:/config
      - /mnt/harddrive/Media/Movies:/data/movies
      - /mnt/harddrive/Media/TV:/data/shows
      - /mnt/harddrive/Media/Martin Garrix Sets:/data/garrix
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    ports:
      - 5055:5055
    networks:
      - servarr
    volumes:
      - ./jellyseerr_config:/app/config
    restart: unless-stopped

networks:
  servarr:
    name: servarr
    external: true
