version: '3.8'

services:
  fullfeedrss:
    image: "heussd/fivefilters-full-text-rss:latest"
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    volumes:
      - ./fullfeedrss_cache:/var/www/html/cache/rss
    ports:
      - "8073:80"

  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    restart: always
    ports:
      - "8072:80"
    environment:
      TZ: Asia/Kolkata
      CRON_MIN: "1,31"
    volumes:
      - ./freshrss_data:/var/www/FreshRSS/data
      - ./freshrss_extensions:/var/www/FreshRSS/extensions

