services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: "host"    
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
