services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - /mnt/harddrive/Media/TV:/tv #optional
      - /home/milind/Downloads/qbittorrent:/downloads #optional
    ports:
      - 8989:8989
    networks:
      - servarr
    restart: unless-stopped

networks:
  servarr:
    name: servarr
    external: true
